version: "3.5"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OPENSTATES_API_KEY=${OPENSTATES_API_KEY}
    ports:
      - 8080:8080
    volumes:
      - $PWD:/tmp
